[theme]
name = "catppuccin"

[theme.custom]
red = "#ff1744"
peach = "#ff9100"
yellow = "#ffea00"
green = "#00e676"
mauve = "#d05cff"
teal = "#00e5ff"
accent = "#00e5ff"
overlay0 = "#7d8798"
subtext0 = "#c3cbd9"

[ui]
agent_panel_sort = "priority"

[ui.sidebar.agents]
rows = [
    [{ token = "state_icon", bold = true }, "workspace", "tab"],
    ["terminal_title"],
    [{ token = "state_text", bold = true }, "agent"],
]

[ui.sidebar.spaces]
rows = [
    [{ token = "state_icon", bold = true }, "workspace"],
    ["branch", "git_status"],
]

[keys]
prefix = "ctrl+space"
detach = "prefix+d"
split_vertical = "prefix+\""
split_horizontal = "prefix+%"

[[keys.command]]
key = "prefix+t"
type = "plugin_action"
command = "herdr-navigator.open"
description = "jump to anything"

[[keys.command]]
key = "prefix+minus"
type = "plugin_action"
command = "herdr-navigator.jump-back"
description = "jump to previous workspace"

[[keys.command]]
key = "prefix+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer"
description = "open file viewer in split"

[[keys.command]]
key = "prefix+shift+f"
type = "plugin_action"
command = "herdr-file-viewer.open-file-viewer-tab"
description = "open file viewer in tab"
