#!/bin/sh

system_type=$(uname -s)

echo "$system_type"
echo "home: $HOME"
ls -als $HOME
if [ "$system_type" = "Darwin" ]; then

  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global --file $HOME/.Brewfile
    echo "installing nvim plugins"
    nvim +PlugInstall +UpdateRemotePlugins +qa

    echo "installing powerline fonts"
    # clone
    git clone https://github.com/powerline/fonts.git --depth=1
    # install
    cd fonts
    ./install.sh
    # clean-up a bit
    cd ..
    rm -rf fonts

    echo "setup fzf"
    $(brew --prefix)/opt/fzf/install
  fi

  asdf plugin add asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git
  asdf install asdf-plugin-manager 1.1.1
  asdf global asdf-plugin-manager 1.1.1

  # asdf plugin-add golang https://github.com/asdf-community/asdf-golang.git
  # asdf install golang latest
  # asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git
  # asdf install terraform latest
  # asdf plugin-add python
  # asdf install python latest
  # asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  # asdf install nodejs latest

fi

#NOTEPAD_DIR="$HOME/dev/notepad"
#[ ! -d "$NOTEPAD_DIR" ] && git clone git@github.com:socialviolation/notepad.git ${NOTEPAD_DIR}
