#!/bin/sh

system_type=$(uname -s)

echo "$system_type"
echo "home: $HOME"
ls -als $HOME
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global --file $HOME/.Brewfile
    echo "installing nvim plugins"
    nvim +PlugInstall +UpdateRemotePlugins +qa

    echo "installing powerline fonts"
    # clone
    git clone https://github.com/powerline/fonts.git --depth=1
    # install
    cd fonts
    ./install.sh
    # clean-up a bit
    cd ..
    rm -rf fonts
  fi

fi