#!/usr/bin/env bash

selected=$(find ${HOME}/dev/ ${HOME}/dev/navexa ${HOME}/dev/wattle -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z $selected ]]; then
    echo "not selected?"
    exit 0
fi
echo $selected
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    echo "new session"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi
echo "joining session"
tmux attach-session -t $selected_name
